//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivityLog
    {
        public int ActivityLogId { get; set; }
        public Nullable<int> AssignementId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string Description { get; set; }
    
        public virtual tblAssignment tblAssignment { get; set; }
        public virtual tblStudent tblStudent { get; set; }
        public virtual tblTeacher tblTeacher { get; set; }
    }
}
