//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignmentSubmission
    {
        public int AssignmentSubmissionId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> AssignmentId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string IsOnTime { get; set; }
    
        public virtual tblAssignment tblAssignment { get; set; }
        public virtual tblStatu tblStatu { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
