//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeacherSubjectMapping
    {
        public int TeacherSubjectMappingId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> SubjectId { get; set; }
    
        public virtual tblSubject tblSubject { get; set; }
        public virtual tblTeacher tblTeacher { get; set; }
    }
}
